import { StyleSheet } from "@react-pdf/renderer";

export const styles = StyleSheet.create({
  page: {
    paddingTop: 36,
    paddingBottom: 36,
    paddingLeft: 48,
    paddingRight: 48,
    fontFamily: "Helvetica",
    fontSize: 10,
    color: "#111",
    lineHeight: 1.35,
  },
  name: {
    fontSize: 22,
    lineHeight: 1.2,
    textAlign: "center",
    fontFamily: "Helvetica-Bold",
    letterSpacing: 1,
  },
  headline: {
    fontSize: 12,
    textAlign: "center",
    color: "#444",
    marginTop: 3,
  },
  contactRow: {
    flexDirection: "row",
    justifyContent: "center",
    flexWrap: "wrap",
    marginTop: 8,
    fontSize: 9.5,
    color: "#222",
  },
  contactItem: { marginHorizontal: 4 },
  contactSep: { marginHorizontal: 2, color: "#888" },
  link: { color: "#1f4ea8", textDecoration: "none" },
  sectionHeader: {
    marginTop: 12,
    paddingBottom: 2,
    borderBottomWidth: 0.75,
    borderBottomColor: "#000",
    fontFamily: "Helvetica-Bold",
    fontSize: 11,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  summary: { marginTop: 6, textAlign: "justify" },
  entryBlock: { marginTop: 6 },
  entryHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
  },
  entryTitle: { fontFamily: "Helvetica-Bold", fontSize: 10.5, flex: 1 },
  entryRight: { fontFamily: "Helvetica-Bold", fontSize: 10, marginLeft: 8 },
  entrySubRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    fontStyle: "italic",
    marginTop: 1,
    fontSize: 9.5,
  },
  bulletList: { marginTop: 3, paddingLeft: 10 },
  bulletRow: { flexDirection: "row", marginTop: 1.5 },
  bulletDot: { width: 8, fontSize: 10 },
  bulletText: { flex: 1, textAlign: "justify" },
  skillRow: { flexDirection: "row", marginTop: 2 },
  skillGroup: { fontFamily: "Helvetica-Bold", marginRight: 4 },
  skillItems: { flex: 1 },
  entryNote: { marginTop: 2, fontStyle: "italic" },
  projectKeywords: { marginTop: 1, fontSize: 9.5, color: "#333" },
  educationDetails: { marginTop: 2 },
});
